### ISSUE TITLE
Add "New @tagged object" action

### ISSUE THREAD

**Issue by rpiotrow** [theiterators/kebs-intellij#4]
Add code template (see File > Settings > Editor > File and Code Templates) and action to use that template in "File > New > Kebs `@tagged` object" in window menu or "New > Kebs `@tagged` object" in context menu (e.g. in project explorer, see below screenshot).

![Screenshot from 2021-02-24 13-54-13](https://user-images.githubusercontent.com/355631/109003913-4fc7a780-76a8-11eb-8316-dbaeac39ed5a.png)

Example of created file using template:
```scala
package pl.iterators.kebs.example3

import pl.iterators.kebs.tagged._
import pl.iterators.kebs.tag.meta.tagged

@tagged object Tags {
  
}
```

**Comment by luksow** [comment]
:-1: at least for me. I have several conventions over couple of projects and it just wouldn't be useful for me.

**Comment by rpiotrow** [comment]
Closing it. We have "Generate @tagged object" action in Generate context menu for case class. This feature seems to be obsolete.
